# Generated by Django 3.1.7 on 2021-02-22 18:28

import creator.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Title')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to=creator.models.schema_directory_path, verbose_name='File path')),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('processing', 'Processing'), ('error', 'Error')], default='processing', max_length=16, verbose_name='Status')),
                ('rows', models.IntegerField(default=50, verbose_name='Rows')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modified')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.schema')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_name', models.CharField(max_length=64, verbose_name='Column name')),
                ('col_type', models.CharField(choices=[('email', 'Email'), ('full_name', 'Full Name'), ('job', 'Job'), ('phone_name', 'Phone Name'), ('company_name', 'Company Name'), ('integer', 'Integer'), ('address', 'Address'), ('date', 'Date')], max_length=16, verbose_name='Type')),
                ('range_from', models.IntegerField(default=0, verbose_name='Range From')),
                ('range_to', models.IntegerField(default=1, verbose_name='Range To')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.schema')),
            ],
        ),
    ]
