# Generated by Django 3.1.7 on 2021-02-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_auto_20210223_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='range_from',
            field=models.IntegerField(blank=True, default=0, verbose_name='Range From'),
        ),
        migrations.AlterField(
            model_name='column',
            name='range_to',
            field=models.IntegerField(blank=True, default=10, verbose_name='Range To'),
        ),
    ]
