# Generated by Django 3.1.7 on 2021-02-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0003_auto_20210224_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='range_from',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Range From'),
        ),
        migrations.AlterField(
            model_name='column',
            name='range_to',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='Range To'),
        ),
    ]
